//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSShortcut.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSShortcut.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;shortcut&gt;
        ///	&lt;mode name=&quot;Main&quot;&gt;
        ///		&lt;group name=&quot;文件&quot;&gt;
        ///			&lt;item command=&quot;CMD_NEW_MODEL&quot; shortcut=&quot;Ctrl+N&quot; /&gt;
        ///			&lt;item command=&quot;CMD_NEW_ANIMATION&quot; shortcut=&quot;Ctrl+Shift+N&quot; /&gt;
        ///			&lt;item command=&quot;CMD_OPEN&quot; shortcut=&quot;Ctrl+O&quot; /&gt;
        ///			&lt;item command=&quot;CMD_RECENT_FILE_OPEN&quot; shortcut=&quot;Ctrl+Shift+O&quot; /&gt;
        ///			&lt;item command=&quot;CMD_DEL_TAB_TABBOX&quot; shortcut=&quot;Ctrl+W&quot; /&gt;
        ///			&lt;item command=&quot;CMD_CLOSE_ALL&quot; /&gt;
        ///			&lt;item command=&quot;CMD_SAVE&quot; shortcut=&quot;Ctrl+S&quot; /&gt;
        ///			&lt;item command=&quot;CMD_SAVE_AS&quot; sh [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string shortcutDefault_Live2D {
            get {
                return ResourceManager.GetString("shortcutDefault_Live2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ,文件
        ///新建模型文件,CMD_NEW_MODEL
        ///新建动画文件,CMD_NEW_ANIMATION
        ///打开指定文件,CMD_OPEN
        ///打开最后一次保存关闭的文件,CMD_RECENT_FILE_OPEN
        ///关闭当前文件,CMD_DEL_TAB_TABBOX
        ///关闭所有文件,CMD_CLOSE_ALL
        ///保存,CMD_SAVE
        ///另存为…,CMD_SAVE_AS
        ///应用模板,CMD_MODELING_TEMPLATE
        ///打开物理/场景混合设定,CMD_SHOW_VIEWER
        ///导出模型为图片,CMD_EXPORT_MODEL_AS_PNG
        ///导出模型为PSD,CMD_EXPORT_MODEL_AS_PSD
        ///导出场景为GIF,CMD_EXPORT_SCENE_AS_ANIMATED_GIF
        ///导出场景为PNG,CMD_EXPORT_SCENE_AS_PNG
        ///导出为moc3文件,CMD_EXPORT_EMBEDDED_MODEL
        ///导出动态文件,CMD_EXPORT_MOTION
        ///导出为视频,CMD_EXPORT_SCENE_AS_VIDEO
        ///网格设定,CMD_GRID_SETTING_SPLIT_I [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string trans_CN_Live2D {
            get {
                return ResourceManager.GetString("trans_CN_Live2D", resourceCulture);
            }
        }
    }
}
